// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Caml_obj = require("bs-platform/lib/js/caml_obj.js");

function destutter(_l) {
  while(true) {
    var l = _l;
    if (!l) {
      return /* [] */0;
    }
    var match = l.tl;
    var x = l.hd;
    if (!match) {
      return {
              hd: x,
              tl: /* [] */0
            };
    }
    var rest = match.tl;
    var y = match.hd;
    if (!Caml_obj.caml_equal(x, y)) {
      return {
              hd: x,
              tl: destutter({
                    hd: y,
                    tl: rest
                  })
            };
    }
    _l = {
      hd: y,
      tl: rest
    };
    continue ;
  };
}

exports.destutter = destutter;
/* No side effect */
