// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Channel$ChannelMedium = require("./Channel.bs.js");

function end$prime(param) {
  return /* () */0;
}

function filter(source, pred) {
  var target = Channel$ChannelMedium.create(/* () */0);
  Channel$ChannelMedium.listen(source, (function (m) {
          var match = Curry._1(pred, m);
          if (match) {
            Channel$ChannelMedium.send(target, m);
            return /* () */0;
          } else {
            return /* () */0;
          }
        }));
  return Channel$ChannelMedium.to_read_only(target);
}

var chan = Channel$ChannelMedium.create(/* () */0);

Channel$ChannelMedium.listen(filter(chan, (function (i) {
            return i > 0;
          })), (function (i) {
        console.log("i>0", i);
        return /* () */0;
      }));

Channel$ChannelMedium.send(Channel$ChannelMedium.send(Channel$ChannelMedium.send(Channel$ChannelMedium.send(chan, 1), -1), 13), 4);

Channel$ChannelMedium.send(chan, 2);

exports.end$prime = end$prime;
exports.filter = filter;
exports.chan = chan;
/* chan Not a pure module */
