// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var App$ParcelRouter = require("./App.bs.js");

ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, App$ParcelRouter.make(/* array */[])), "root");

var match = module.hot;

if (match == null) {
  console.log("We are not hot");
} else {
  match.accept();
}

/*  Not a pure module */
